exports.SOCKET = {
  CONNECTION: "connection",
  JOINROOM: "join-room",
  SOCKET_ID: "socket-id",
  ALL_USRS: "all users",
  USER_COUNT: "user-count",
  ROLE_COUNT: "role-count",
  ROLE_COUNTS: "role-counts",
  USER_INFO: "user-info",
  USER_INFO_UPDATE: "user-info-update",
  READY: "ready",
  ENTER_GAME: "enter",
  ALL_INFO: "all-info",
  SENDING_SIGNAL: "sending signal",
  USER_JOINED: "user joined",
  RETURNING_SIGNAL: "returning signal",
  RECEIVING_RETURNED_SIGNAL: "receiving returned signal",
  MOTION_START: "motion-start",
  START: "start",
  MOVED: "moved",
  REMAINING_OPPORTUNITY: "remaining-opportunity",
  PARTICIPANT_REMAINING_COUNT: "participant-remaining-count",
  GAME_END: "game-end",
  ANOTHER_USER_END: "another-user-end",
  DISCONNECT: "disconnect",
};
