exports.SOCKET = {
  CONNECTION: "connection",
  ROOM_LIST: "roomList",
  CREATE_GAME: "createGame",
  ROOM_INFO: "room-info",
  JOINROOM: "join-room",
  NEW_ROOM: "new-room",
  SOCKET_ID: "socket-id",
  ALL_USRS: "all users",
  USER_COUNT: "user-count",
  ROLE_COUNT: "role-count",
  ROLE_COUNTS: "role-counts",
  USER_INFO: "user-info",
  USER_INFO_UPDATE: "user-info-update",
  READY: "ready",
  ENTER_GAME: "enter",
  ALL_INFO: "all-info",
  SENDING_SIGNAL: "sending signal",
  USER_JOINED: "user joined",
  RETURNING_SIGNAL: "returning signal",
  RECEIVING_RETURNED_SIGNAL: "receiving-returned-signal",
  IS_READY: "isReady",
  PREPARED_GAME: "prepared-game",
  PREPARED: "prepared",
  MOTION_START: "motion-start",
  START: "start",
  MOVED: "moved",
  REMAINING_OPPORTUNITY: "remaining-opportunity",
  PARTICIPANT_REMAINING_COUNT: "participant-remaining-count",
  GAME_END: "game-end",
  ANOTHER_USER_END: "another-user-end",
  COUNT_END: "count-end",
  IT_END: "it-end",
  IT_LOSER: "itLoser",
  IT_LOSER_GAME_END: "itLoser-gameEnd",
  INFO_INITIALIZATION: "infoInitialization",
  DISCONNECT: "disconnect",
  LEAVE_ROOM: "leaveRoom",
  UPDATE_USER: "updateUser",
  ALL_READY: "all-ready",
  GO_GAME: "goGame",
  POSEDETECTION_START: "poseDetection-start",
  CLICK_COUNT_NONE: "clickCount none",
  USER_LEFT: "userLeft",
};
